# This is a basic workflow to help you get started with Actions

name: Launch Hello World

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run:
        description: 'Name of this run'
        required: true
        type: string
        default: 'run'
      experiment:
        description: 'The name of this experiment the pipeline'
        required: true
        default: 'experiment'
      message:
        description: 'The message you want to send'
        required: true
        default: 'Hello World!'

  workflow_call:
    secrets:
      deploykf_host:
        description: 'The Host Where Deploykf is running'
        required: true
      deploykf_user:
        description: 'The user launching the pipeline'
        required: true
      deploykf_password:
        description: 'The users password launching the pipeline'
        required: true
      deploykf_namespace:
        description: 'The namespace launching the pipeline'
        required: true
        
jobs:
  run_pipeline:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install project
        run: make install
      - name: Launch Pipeline
        run: kubeflow_pipeline

        env:
          DEPLOYKF_HOST: ${{ secrets.DEPLOYKF_HOST }}
          DEPLOYKF_USER: ${{ secrets.DEPLOYKF_USER }}
          DEPLOYKF_PASSWORD: ${{ secrets.DEPLOYKF_PASSWORD }}
          DEPLOYKF_NAMESPACE: ${{ secrets.DEPLOYKF_NAMESPACE }}
          DEPLOYKF_EXPERIMENT: ${{ inputs.experiment }}
          DEPLOYKF_RUN: ${{ inputs.run }}
          PIPELINE_NAME: 'hello_world'
          MESSAGE: ${{ inputs.message }}