# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      host:
        description: 'The host (no scheme/port) of your kubeflow instance'
        required: true
      username:
        description: 'The username for the kubeflow pipeline account'
        required: true
      password:
        description: 'The password for the kubeflow pipeline account'
        required: true
        type: string
      namespace:
        description: 'The Kubeflow Namespace to run the work in'
        required: true
        type: string
      experiment:
        description: 'The name of this experiment the pipeline should run in '
        required: true
        default: 'test'
      run:
        description: 'Name of this run'
        required: true
        type: string
        default: 'run'
      message:
        description: 'The message you want to print'
        required: true
        default: 'Hello World!'

  workflow_call:
    secrets:
      deploykf_host:
        description: 'The Host Where Deploykf is running'
        required: true
      deploykf_user:
        description: 'The user launching the pipeline'
        required: true
      deploykf_password:
        description: 'The users password launching the pipeline'
        required: true
      deploykf_namespace:
        description: 'The namespace launching the pipeline'
        required: true
        
jobs:
  run_pipeline:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install poetry
        run: pip install poetry
      - name: Install project
        run: poetry install
      - name: Launch Pipeline
        run: >
          poetry run kubeflow-pipeline 
          --host $DEPLOYKF_HOST
          --namespace $DEPLOYKF_NAMESPACE 
          --experiment $DEPLOYKF_EXPERIMENT 
          --username $DEPLOYKF_USER
          --password $DEPLOYKF_PASSWORD 
          --pipeline $PIPELINE_NAME 
          --args '{"message": "'$MESSAGE'"}'


        env:
          DEPLOYKF_HOST: ${{ inputs.host }}
          DEPLOYKF_USER: ${{ inputs.username }}
          DEPLOYKF_PASSWORD: ${{ inputs.password }}
          DEPLOYKF_NAMESPACE: ${{ inputs.namespace }}
          DEPLOYKF_EXPERIMENT: ${{ inputs.experiment }}
          DEPLOYKF_RUN: ${{ inputs.run }}
          PIPELINE_NAME: 'hello_world'
          MESSAGE: ${{ inputs.message }}