# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./ajperry_pipeline"

  build-and-test:
    environment: pipeline_env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Specify your desired Python version
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: pip install -e .[test]
    - name: Run tests
      run: poetry run pytest # Example for running tests with pytest
      env:
          KUBEFLOW_HOST: ${{ secrets.KUBEFLOW_HOST }}
          KUBEFLOW_USER: ${{ secrets.KUBEFLOW_USER }}
          KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_PASSWORD }}
          KUBEFLOW_NAMESPACE: ${{ secrets.KUBEFLOW_NAMESPACE }}
