# This is a basic workflow to help you get started with Actions

name: Download Nuscene

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      experiment:
        description: 'The name of this experiment the pipeline'
        required: true
        default: 'test'
      run:
        description: 'Name of this run'
        required: true
        type: string
        default: 'run'
      nuscene_email:
        description: 'The email for your nuscene account'
        required: true
        type: string
      nuscene_password:
        description: 'The password for your nuscene account'
        required: true
        type: string

  workflow_call:
    secrets:
      KUBEFLOW_HOST:
        description: 'The Host Where KUBEFLOW is running'
        required: true
      KUBEFLOW_user:
        description: 'The user launching the pipeline'
        required: true
      KUBEFLOW_password:
        description: 'The users password launching the pipeline'
        required: true
      KUBEFLOW_namespace:
        description: 'The namespace launching the pipeline'
        required: true
        
jobs:
  run_pipeline:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    environment: pipeline_env
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install poetry
        run: pip install poetry
      - name: Install project
        run: poetry install
      - name: Launch Pipeline
        run: >
          poetry run kubeflow-pipeline 
          --host ${{ secrets.KUBEFLOW_HOST }}
          --namespace ${{ secrets.KUBEFLOW_NAMESPACE }}
          --experiment $KUBEFLOW_EXPERIMENT 
          --username ${{ secrets.KUBEFLOW_USER }}
          --password ${{ secrets.KUBEFLOW_PASSWORD }}
          --pipeline download_nuscene 
          --args '{"nuscene_email": "'$NUSCENE_EMAIL'","nuscene_password": "'$NUSCENE_PASSWORD'","region": "us"}'
        env:
          KUBEFLOW_EXPERIMENT: ${{ inputs.experiment }}
          KUBEFLOW_RUN: ${{ inputs.run }}
          NUSCENE_EMAIL: ${{ inputs.nuscene_email }}
          NUSCENE_PASSWORD: ${{ inputs.nuscene_password }}