# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run:
        description: 'Experiment this run will be called'
        required: true
        type: string
      namespace:
        description: 'The namespace for grouping the pipeline'
        required: true
        default: 'test'

  workflow_call:
    secrets:
      deploykf_host:
        description: 'The Host Where Deploykf is running'
        required: true
      deploykf_user:
        description: 'The user launching the pipeline'
        required: true
      deploykf_password:
        description: 'The users password launching the pipeline'
        required: true
        
jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install project
        run: make install
      - name: Launch Pipeline
        run: make launch

        env:
          deploykf_host: ${{ secrets.deploykf_host }}
          deploykf_user: ${{ secrets.deploykf_user }}
          deploykf_password: ${{ secrets.deploykf_password }}
          deploykf_namespace: ${{ inputs.namespace }}
          deploykf_run: ${{ inputs.run }}